export type Locale = "en" | "sw";

export const LOCALES: Locale[] = ["en", "sw"];
export const DEFAULT_LOCALE: Locale = "en";

/**
 * Every user-visible string in the product, in both languages.
 * A screen is not finished until it fits in both — `sw` is typed against the
 * English table, so a missing translation is a compile error, and `t` requires
 * an explicit locale so nothing silently ships in one language.
 */
const en = {
  // Home — the landing surface, carried over from the earlier Tunza app
  homeTagline: "Healthcare, anywhere, anytime.",
  homeGetStarted: "Get started",
  homeCardAssessTitle: "Check symptoms",
  homeCardAssessDesc: "Text, voice or photo",
  homeCardNearbyTitle: "Nearby facilities",
  homeCardNearbyDesc: "See your area",
  homeCardContinueTitle: "Continue",
  homeMission:
    "Built for community health workers where the nearest doctor may be hours away.",
  homeHealthWorker: "Are you a health worker?",
  gateHeading: "Sign in to continue",
  gateBody:
    "This area is for registered health workers. Choose your role and enter your access code.",
  gateChooseChp: "I'm a community health promoter",
  gateChooseFacility: "I work at a facility",
  gateCodeLabel: "Access code",
  gateSubmit: "Sign in",
  gateChecking: "Checking…",
  gateWrongCode: "That code did not work. Check with your coordinator.",
  gateDemoHint: "Demo codes: CHP-DEMO and FACILITY-DEMO.",
  nearbyTitle: "Nearby facilities",
  nearbyLocating: "Finding facilities near you…",
  nearbyDemoFallback: "Showing demo facilities — live lookup is not available right now.",
  facilityUrgentCapable: "Can take urgent cases",
  facilityGeneralCare: "General care",
  facilityHospital: "Hospital",
  facilityClinic: "Clinic",
  facilityPharmacy: "Pharmacy",
  facilityDistanceTpl: "About {km} km away",
  transcribing: "Transcribing…",

  // Who needs help?
  whoQuestion: "Who needs help?",
  whoSelf: "Me",
  whoAdult: "An adult at home",
  whoChild: "A child",
  whoUnknown: "I'm not sure",

  // What is happening?
  whatQuestion: "What is happening?",
  whatHint: "Say it the way you would tell a neighbour.",
  whatPlaceholder: "Fever, coughing, not drinking…",
  whatContinue: "Continue",

  // Entry modes
  modeSpeak: "Speak",
  modeType: "Type",
  modePhoto: "Photo",
  entryAria: "How to answer",
  typeWhatYouSee: "Type what you see",
  tapToSpeak: "Tap to speak",
  listening: "Listening…",
  speakNotAvailable: "Speak isn't available",
  speakUnavailable: "Speaking isn't available on this device. Type instead.",
  photoTake: "Take or choose a photo",
  photoAttachedDemo: "Photo attached (demo)",
  photoRemove: "Remove photo",
  photoHint:
    "Use this when a rash, wound, or breathing effort is easier to show than to describe.",
  addNote: "Add a short note if you can",

  // One question at a time
  dontKnow: "I don't know",
  back: "Previous",
  awakeQuestion: "Are they awake and responding?",
  awakeAlert: "Yes, alert",
  awakeSleepy: "Sleepy or confused",
  awakeNotWaking: "Not waking up",
  breathingQuestion: "How is their breathing?",
  breathingFine: "Breathing looks fine",
  breathingDifficult: "Fast or hard to breathe",
  breathingSevere: "Struggling to breathe",
  drinkingQuestion: "Can they drink?",
  drinkingQuestionChild: "Can they drink or breastfeed?",
  drinkingYes: "Yes",
  drinkingLittle: "Only a little",
  drinkingNo: "No",
  durationQuestion: "How long has this been going on?",
  durationToday: "Started today",
  durationTwoDays: "1–2 days",
  durationLonger: "Longer than that",
  mainProblemQuestion: "What is the main problem right now?",
  mainBreathing: "Breathing",
  mainFever: "Fever",
  mainInjury: "Injury or bleeding",
  mainStomach: "Stomach or not eating",
  mainOther: "Something else",

  // The decision
  nextAction: "Next action",
  goNow: "Go now",
  getCareToday: "Get care today",
  monitorAtHome: "Monitor at home",
  needOneMore: "I need one more answer",
  goNowStatus: "This looks urgent. Do not wait.",
  getCareStatus: "They should be seen today, not next week.",
  monitorStatus: "Stay home for now, and watch these signs.",
  needOneMoreStatus: "One question would make this safer.",
  prepareFacility: "Get a facility ready",
  createReferral: "Create referral",
  answerTheQuestion: "Answer the question",
  whyThis: "Why this?",
  moreDetail: "More detail",

  // Danger signs
  dangerNotWaking: "Not waking",
  dangerSeizure: "Seizure",
  dangerNotBreathing: "Not breathing",
  dangerBlueLips: "Blue lips",
  dangerHeavyBleeding: "Heavy bleeding",
  dangerStrugglingBreathe: "Struggling to breathe",
  dangerChildNoDrink: "Child cannot drink",

  // Watch signs
  watchNotWaking: "Not waking or very sleepy",
  watchBreathingHard: "Breathing gets hard or fast",
  watchCannotDrink: "Cannot drink",
  watchSeizureBleeding: "Seizure or heavy bleeding",

  // Reasons behind the decision
  reasonSleepyHardBreathing: "Sleepy and breathing is hard",
  reasonTooLittleKnown: "Too little is known to choose safely",
  reasonOneMoreSafer: "One more question would make this safer",
  reasonBreathingHarder: "Breathing is harder than usual",
  reasonDrinkingLittle: "Drinking only a little",
  reasonNotDrinking: "Not drinking",
  reasonSleepy: "Sleepy or harder to wake",
  reasonChildFever: "Child with fever",
  reasonInjurySeen: "Injury that should be seen",
  reasonBreathingMain: "Breathing is the main problem",
  reasonTooLongHome: "This has gone on too long to only watch at home",
  reasonNoDanger: "Awake, drinking, and breathing do not show a danger sign",

  // Missing information
  missingWho: "Who this is for is not clear",
  missingWhoDetail: "Child, adult, or self changes what we ask next.",
  missingWhat: "What is happening was not described",
  missingAwake: "Awake and responding is unknown",
  missingBreathing: "Breathing is unknown",
  missingDrinking: "Whether they can drink is unknown",
  missingAskMoreDetail: "The facility asked for this before accepting.",
  askMoreCanWalk: "Can they walk into the facility?",

  // Referral — stage labels (human words, never the internal names)
  referralEyebrow: "Referral",
  stageCreated: "Being prepared",
  stageSent: "Sent",
  stageReceived: "Received",
  stageAccepted: "Accepted",
  stagePatientMoving: "Patient traveling",
  stageArrived: "Arrived",
  stageSeen: "Being seen",
  stageCompleted: "Visit complete",
  stageOutcomeReturned: "Outcome returned",

  // Referral — the same event, per role
  refCreatedHouseholdHeadline: "A facility is being prepared",
  refCreatedHouseholdStatus: "Nothing has been sent yet.",
  refCreatedChpHeadline: "Referral prepared — not sent yet",
  refCreatedChpStatus: "Ready for {f}.",
  refCreatedFacilityHeadline: "A community referral is being prepared",
  refCreatedFacilityStatus: "It has not reached this facility yet.",
  refSentHouseholdHeadline: "Your referral is on the way",
  refSentHouseholdStatus: "{f} has not answered yet.",
  refSentChpHeadline: "Referral sent — waiting for the facility",
  refSentChpStatus: "{f} has not accepted yet.",
  refSentFacilityHeadline: "New referral — not yet reviewed",
  refSentFacilityStatus: "Decide whether this facility can take them.",
  refReceivedHouseholdHeadline: "The facility has seen your referral",
  refReceivedHouseholdStatus: "They have not accepted yet. Stay ready.",
  refReceivedChpHeadline: "Facility received referral — not yet accepted",
  refReceivedChpStatus: "{f} is deciding now.",
  refReceivedFacilityHeadline: "Referral received — decide now",
  refReceivedFacilityStatus: "Accept, redirect, or ask for one missing fact.",
  refAcceptedHouseholdHeadline: "Facility accepted — you can leave now",
  refAcceptedHouseholdStatus: "Go to {f}.",
  refAcceptedChpHeadline: "Referral accepted — patient travel not yet confirmed",
  refAcceptedChpStatus: "{f} is waiting for them to leave.",
  refAcceptedFacilityHeadline: "Incoming referral",
  refAcceptedFacilityUrgentHeadline: "Incoming urgent referral",
  refAcceptedFacilityStatus: "Prepare to receive them.",
  refMovingHouseholdHeadline: "You're on the way. They know you're coming.",
  refMovingHouseholdStatus: "Tell them you are the Tunza referral at {f}.",
  refMovingChpHeadline: "Patient traveling — arrival not yet confirmed",
  refMovingChpStatus: "{f} is expecting them.",
  refMovingFacilityHeadline: "Patient en route — prepare to receive",
  refMovingFacilityStatus: "Keep the receiving place ready.",
  refArrivedHouseholdHeadline: "You've arrived. Tell them you're the Tunza referral.",
  refArrivedHouseholdStatus: "Stay until they have seen you.",
  refArrivedChpHeadline: "Patient arrived — visit not yet closed",
  refArrivedChpStatus: "They are at the facility.",
  refArrivedFacilityHeadline: "Patient here — start care",
  refArrivedFacilityStatus: "The person has arrived.",
  refSeenHouseholdHeadline: "They are being seen now",
  refSeenHouseholdStatus: "Stay until the visit is finished.",
  refSeenChpHeadline: "Patient being seen — visit not yet closed",
  refSeenChpStatus: "The outcome comes after the visit is closed.",
  refSeenFacilityHeadline: "In care — close the visit when done",
  refSeenFacilityStatus: "Record what happened when care is finished.",
  refCompletedHouseholdHeadline: "Care is finished. Waiting to hear what happened.",
  refCompletedHouseholdStatus: "The outcome has not come back yet.",
  refCompletedChpHeadline: "Visit completed — waiting for outcome",
  refCompletedChpStatus: "Follow-up depends on what the facility returns.",
  refCompletedFacilityHeadline: "Visit complete — return the outcome",
  refCompletedFacilityStatus: "The community needs to know what happened.",
  refOutcomeHouseholdHeadline: "Here's what happened, and what to do next",
  refOutcomeHouseholdStatus: "The facility returned an outcome.",
  refOutcomeChpHeadline: "Outcome returned — follow-up may be needed",
  refOutcomeChpStatus: "Review whether this household needs a visit.",
  refOutcomeFacilityHeadline: "Outcome sent to the community",
  refOutcomeFacilityStatus: "Returned.",
  refQueuedHouseholdHeadline: "Saved on this phone",
  refQueuedHouseholdStatus: "You're offline. The referral will send when you're back.",
  refQueuedChpHeadline: "Referral queued — offline",
  refQueuedChpStatus: "It is on this device. Send when the connection returns.",
  refNoResponseHeadline: "No facility response",
  refNoResponseHouseholdStatus: "Stay where you can travel when they answer.",
  refNoResponseOtherStatus: "Referral sent — the facility has not answered.",
  refNoResponseFacilityStatus: "{f} has not responded.",

  // Referral — actions
  actionSendNow: "Send now",
  actionSendFacility: "Send to the facility",
  actionSendReferral: "Send referral",
  actionAccept: "Accept",
  actionWeveLeft: "We've left",
  actionTheyLeft: "They have left",
  actionWeveArrived: "We've arrived",
  actionTheyreHere: "They're here",
  actionStartCare: "Start care",
  actionCompleteVisit: "Complete visit",
  actionReturnOutcome: "Return what happened",

  // Referral — numbers
  expectedArrivalTpl: "expected arrival {m} min",
  travelTpl: "Travel {m} min",

  // Failure states (designed, never generic)
  failOfflineEyebrow: "Offline",
  failOfflineTitle: "You're offline",
  failOfflineBody:
    "The assessment still works on this phone. Sending a referral waits until you are back.",
  failNoResponseEyebrow: "No response",
  failNoResponseTitle: "No facility response",
  failNoResponseBody:
    "The referral left this phone. The facility has not answered. Stay where you can travel when they do.",
  failRedirectedEyebrow: "Redirected",
  failRedirectedTitle: "Redirected to another facility",
  failRedirectedBody:
    "This place cannot take them. Another facility is now on the referral.",
  failStaleEyebrow: "Old information",
  failStaleTitle: "This information may be stale",
  failStaleBody:
    "A recorded value is too old to drive today's decision the same way as a fresh one.",
  failIncompleteEyebrow: "Incomplete",
  failIncompleteTitle: "This assessment is incomplete",
  failIncompleteBody:
    "There is not enough information to make this decision safely. One more answer is required.",
  failWeakEyebrow: "Weak connection",
  failWeakTitle: "Weak connection",
  failWeakBody:
    "This may take longer. The care path stays on this phone until the send is confirmed.",
  dangerEyebrow: "Danger sign",
  dangerTitle: "Do not wait at home with this sign.",
  dangerBody: "Go to care now.",
  watchEyebrow: "Watch",
  watchTitle: "Go now if this starts",

  // Facility card
  facilityEyebrow: "Facility",
  facilityTravelTpl: "{m} min by typical road",
  facilityCanTake: "This facility can take them",
  facilityWeCanHandle: "We can handle this referral",
  facilityMayNot: "This facility may not be able to take them",

  // Handoff
  handoffEyebrow: "Handoff",
  whyComingUrgent:
    "{who} needs urgent care. Danger signs were flagged in the community assessment.",
  whyComingToday: "{who} should be seen today. This is not a wait-at-home case.",
  whyComingDefault: "{who} is on a Tunza referral.",
  whoSubjectChild: "A child from a demo household",
  whoSubjectSelf: "An adult (self) from a demo household",
  whoSubjectOther: "A person from a demo household",
  handoffWho: "Who",
  handoffDescribed: "What they described",
  handoffAwake: "Awake",
  handoffBreathing: "Breathing",
  handoffDrinking: "Drinking",
  handoffDuration: "How long",
  handoffTemp: "Temperature (demo)",
  handoffPhotoOnly: "Photo only (demo)",
  handoffNotDescribed: "Not described",
  handoffStillMissing: "Still missing",
  whoValueSelf: "Adult (self) · demo household",
  whoValueAdult: "Adult · demo household",
  whoValueChild: "Child · demo household",
  whoValueUnknown: "Not specified · demo household",
  unknownValue: "Unknown",
  freshnessAssessedTpl: "assessed {m} min ago",
  freshnessOld: "recorded 8 months ago",

  // Outcome
  outcomeQuestion: "What happened?",
  outcomeTreated: "Seen and treated",
  outcomeHigher: "Needed a higher facility",
  outcomeNoShow: "Did not arrive",
  outcomeUnknown: "Outcome not known",

  // CHP and facility surfaces
  startEncounter: "Start encounter",
  noEncounter: "No active encounter",
  noEncounterDetail: "Start one to capture what is happening, then decide.",
  noIncoming: "No incoming referral",
  noIncomingDetail: "When a household or CHP sends one, it appears here.",
  otherActions: "Other actions",
  redirect: "Redirect",
  askMore: "Ask more",
  needsAttention: "Needs attention",
  needsAction: "Needs action",
  missingInformation: "Missing information",
  whoNeedsFollowUp: "Who needs follow-up",
  nothingWaiting: "Nothing waiting",
  encounterTitle: "Encounter",
  incomingTitle: "Incoming",
  fuWatchHome: "Demo household — watch for danger signs",
  fuWatchHomeDetail:
    "They were advised to stay home. Check they still can drink and wake.",
  fuConfirmTravel: "Travel not yet confirmed",
  fuConfirmTravelDetail: "Facility accepted. Confirm whether the household has left.",
  fuPostOutcome: "Demo household — follow up after care",
  fuPostOutcomeDetail: "Confirm they are improving at home.",

  // Chrome
  viewingAs: "Viewing as",
  roleHousehold: "Household",
  roleChp: "CHP",
  roleFacility: "Facility",
  demoLabel: "Demo",
  namedConditions: "Named conditions",
  startOver: "Start over",
  languageButton: "Kiswahili",
  languageAria: "Badilisha lugha kuwa Kiswahili",
  disclaimer: "Not a substitute for emergency services or professional medical care.",

  contractObservedFacts: "Observed facts",
  contractRetrievedEvidence: "Retrieved evidence",
  contractDerivedFeatures: "Derived features",
  contractHypotheses: "Hypotheses",
  contractUncertainties: "Uncertainties",
  contractContradictions: "Contradictions",
  contractRequiredInformation: "Required information",
  contractRedFlags: "Recorded flags",
  contractNextAction: "Next action",
  contractProvenance: "Provenance",
};

export type CopyKey = keyof typeof en;

const sw: Record<CopyKey, string> = {
  homeTagline: "Huduma ya afya, popote, wakati wowote.",
  homeGetStarted: "Anza",
  homeCardAssessTitle: "Angalia dalili",
  homeCardAssessDesc: "Maandishi, sauti au picha",
  homeCardNearbyTitle: "Vituo vya karibu",
  homeCardNearbyDesc: "Ona eneo lako",
  homeCardContinueTitle: "Endelea",
  homeMission:
    "Imetengenezwa kwa ajili ya wahudumu wa afya ya jamii ambapo daktari wa karibu anaweza kuwa masaa mengi mbali.",
  homeHealthWorker: "Wewe ni mhudumu wa afya?",
  gateHeading: "Ingia ili kuendelea",
  gateBody:
    "Sehemu hii ni ya wahudumu wa afya waliosajiliwa. Chagua nafasi yako na uweke msimbo wako wa kuingia.",
  gateChooseChp: "Mimi ni mhamasishaji wa afya ya jamii",
  gateChooseFacility: "Nafanya kazi katika kituo cha afya",
  gateCodeLabel: "Msimbo wa kuingia",
  gateSubmit: "Ingia",
  gateChecking: "Inakagua…",
  gateWrongCode: "Msimbo huo haukufanya kazi. Wasiliana na mratibu wako.",
  gateDemoHint: "Misimbo ya majaribio: CHP-DEMO na FACILITY-DEMO.",
  nearbyTitle: "Vituo vya karibu",
  nearbyLocating: "Inatafuta vituo karibu nawe…",
  nearbyDemoFallback:
    "Vituo vya majaribio vinaonyeshwa — utafutaji wa moja kwa moja haupatikani sasa.",
  facilityUrgentCapable: "Inaweza kupokea dharura",
  facilityGeneralCare: "Huduma za kawaida",
  facilityHospital: "Hospitali",
  facilityClinic: "Kliniki",
  facilityPharmacy: "Duka la dawa",
  facilityDistanceTpl: "Takriban kilomita {km} kutoka hapa",
  transcribing: "Inanukuu…",

  whoQuestion: "Nani anahitaji msaada?",
  whoSelf: "Mimi",
  whoAdult: "Mtu mzima nyumbani",
  whoChild: "Mtoto",
  whoUnknown: "Sina uhakika",

  whatQuestion: "Nini kinaendelea?",
  whatHint: "Sema kama vile ungemwambia jirani.",
  whatPlaceholder: "Homa, kukohoa, hanywi…",
  whatContinue: "Endelea",

  modeSpeak: "Sema",
  modeType: "Andika",
  modePhoto: "Picha",
  entryAria: "Jinsi ya kujibu",
  typeWhatYouSee: "Andika unachoona",
  tapToSpeak: "Gusa kuongea",
  listening: "Inasikiliza…",
  speakNotAvailable: "Kusema hakupatikani",
  speakUnavailable: "Kusema hakupatikani kwenye kifaa hiki. Andika badala yake.",
  photoTake: "Piga au chagua picha",
  photoAttachedDemo: "Picha imeambatishwa (jaribio)",
  photoRemove: "Ondoa picha",
  photoHint:
    "Tumia hii wakati upele, jeraha, au jinsi anavyopumua ni rahisi kuonyesha kuliko kueleza.",
  addNote: "Ongeza maelezo mafupi ukiweza",

  dontKnow: "Sijui",
  back: "Rudi nyuma",
  awakeQuestion: "Je, yuko macho na anaitika?",
  awakeAlert: "Ndiyo, yuko macho",
  awakeSleepy: "Ana usingizi au amechanganyikiwa",
  awakeNotWaking: "Haamki",
  breathingQuestion: "Anapumuaje?",
  breathingFine: "Anapumua vizuri",
  breathingDifficult: "Anapumua kwa kasi au kwa shida",
  breathingSevere: "Anahangaika kupumua",
  drinkingQuestion: "Je, anaweza kunywa?",
  drinkingQuestionChild: "Je, anaweza kunywa au kunyonya?",
  drinkingYes: "Ndiyo",
  drinkingLittle: "Kidogo tu",
  drinkingNo: "Hapana",
  durationQuestion: "Hii imeendelea kwa muda gani?",
  durationToday: "Imeanza leo",
  durationTwoDays: "Siku 1–2",
  durationLonger: "Zaidi ya hapo",
  mainProblemQuestion: "Tatizo kuu ni nini sasa hivi?",
  mainBreathing: "Kupumua",
  mainFever: "Homa",
  mainInjury: "Jeraha au kutokwa na damu",
  mainStomach: "Tumbo au kutokula",
  mainOther: "Kitu kingine",

  nextAction: "Hatua inayofuata",
  goNow: "Nenda sasa",
  getCareToday: "Pata matibabu leo",
  monitorAtHome: "Angalia nyumbani",
  needOneMore: "Nahitaji jibu moja zaidi",
  goNowStatus: "Hii inaonekana ya dharura. Usisubiri.",
  getCareStatus: "Anapaswa kuonwa leo, si wiki ijayo.",
  monitorStatus: "Kaa nyumbani kwa sasa, na uangalie dalili hizi.",
  needOneMoreStatus: "Swali moja lingefanya hili kuwa salama zaidi.",
  prepareFacility: "Andaa kituo cha afya",
  createReferral: "Tengeneza rufaa",
  answerTheQuestion: "Jibu swali",
  whyThis: "Kwa nini hivi?",
  moreDetail: "Maelezo zaidi",

  dangerNotWaking: "Haamki",
  dangerSeizure: "Kifafa au degedege",
  dangerNotBreathing: "Hapumui",
  dangerBlueLips: "Midomo ya bluu",
  dangerHeavyBleeding: "Kutokwa na damu nyingi",
  dangerStrugglingBreathe: "Anahangaika kupumua",
  dangerChildNoDrink: "Mtoto hawezi kunywa",

  watchNotWaking: "Haamki au ana usingizi mzito",
  watchBreathingHard: "Kupumua kunakuwa kugumu au kwa kasi",
  watchCannotDrink: "Hawezi kunywa",
  watchSeizureBleeding: "Kifafa au kutokwa na damu nyingi",

  reasonSleepyHardBreathing: "Ana usingizi na anapumua kwa shida",
  reasonTooLittleKnown: "Kinachojulikana ni kidogo mno kuchagua kwa usalama",
  reasonOneMoreSafer: "Swali moja zaidi lingefanya hili kuwa salama zaidi",
  reasonBreathingHarder: "Anapumua kwa shida kuliko kawaida",
  reasonDrinkingLittle: "Anakunywa kidogo tu",
  reasonNotDrinking: "Hanywi",
  reasonSleepy: "Ana usingizi au ni vigumu kumwamsha",
  reasonChildFever: "Mtoto mwenye homa",
  reasonInjurySeen: "Jeraha linalopaswa kuonwa",
  reasonBreathingMain: "Kupumua ndilo tatizo kuu",
  reasonTooLongHome: "Imeendelea muda mrefu mno kuangalia nyumbani tu",
  reasonNoDanger: "Yuko macho, anakunywa, na kupumua hakuonyeshi dalili ya hatari",

  missingWho: "Ni nani anayehusika haijabainika",
  missingWhoDetail: "Mtoto, mtu mzima, au wewe mwenyewe hubadilisha tunachouliza.",
  missingWhat: "Kinachoendelea hakikuelezwa",
  missingAwake: "Kuwa macho na kuitika hakujulikani",
  missingBreathing: "Hali ya kupumua haijulikani",
  missingDrinking: "Kama anaweza kunywa hakujulikani",
  missingAskMoreDetail: "Kituo kiliuliza hili kabla ya kukubali.",
  askMoreCanWalk: "Je, anaweza kutembea hadi ndani ya kituo?",

  referralEyebrow: "Rufaa",
  stageCreated: "Inaandaliwa",
  stageSent: "Imetumwa",
  stageReceived: "Imepokelewa",
  stageAccepted: "Imekubaliwa",
  stagePatientMoving: "Mgonjwa safarini",
  stageArrived: "Amefika",
  stageSeen: "Anaonwa",
  stageCompleted: "Ziara imekamilika",
  stageOutcomeReturned: "Matokeo yamerejeshwa",

  refCreatedHouseholdHeadline: "Kituo cha afya kinaandaliwa",
  refCreatedHouseholdStatus: "Hakuna kilichotumwa bado.",
  refCreatedChpHeadline: "Rufaa imeandaliwa — haijatumwa bado",
  refCreatedChpStatus: "Iko tayari kwa {f}.",
  refCreatedFacilityHeadline: "Rufaa ya jamii inaandaliwa",
  refCreatedFacilityStatus: "Bado haijafika kituo hiki.",
  refSentHouseholdHeadline: "Rufaa yako iko njiani",
  refSentHouseholdStatus: "{f} bado haijajibu.",
  refSentChpHeadline: "Rufaa imetumwa — inasubiri kituo",
  refSentChpStatus: "{f} bado haijakubali.",
  refSentFacilityHeadline: "Rufaa mpya — bado haijakaguliwa",
  refSentFacilityStatus: "Amua kama kituo hiki kinaweza kumpokea.",
  refReceivedHouseholdHeadline: "Kituo kimeona rufaa yako",
  refReceivedHouseholdStatus: "Bado hawajakubali. Kaa tayari.",
  refReceivedChpHeadline: "Kituo kimepokea rufaa — bado haijakubaliwa",
  refReceivedChpStatus: "{f} inaamua sasa.",
  refReceivedFacilityHeadline: "Rufaa imepokelewa — amua sasa",
  refReceivedFacilityStatus: "Kubali, elekeza kwingine, au uliza jambo moja linalokosekana.",
  refAcceptedHouseholdHeadline: "Kituo kimekubali — unaweza kuondoka sasa",
  refAcceptedHouseholdStatus: "Nenda {f}.",
  refAcceptedChpHeadline: "Rufaa imekubaliwa — safari ya mgonjwa haijathibitishwa",
  refAcceptedChpStatus: "{f} inasubiri waondoke.",
  refAcceptedFacilityHeadline: "Rufaa inakuja",
  refAcceptedFacilityUrgentHeadline: "Rufaa ya dharura inakuja",
  refAcceptedFacilityStatus: "Jiandae kumpokea.",
  refMovingHouseholdHeadline: "Uko njiani. Wanajua unakuja.",
  refMovingHouseholdStatus: "Waambie wewe ni rufaa ya Tunza katika {f}.",
  refMovingChpHeadline: "Mgonjwa yuko safarini — kufika hakujathibitishwa",
  refMovingChpStatus: "{f} inamtarajia.",
  refMovingFacilityHeadline: "Mgonjwa yuko njiani — jiandae kupokea",
  refMovingFacilityStatus: "Weka mahali pa kupokea tayari.",
  refArrivedHouseholdHeadline: "Umefika. Waambie wewe ni rufaa ya Tunza.",
  refArrivedHouseholdStatus: "Kaa hadi wakuone.",
  refArrivedChpHeadline: "Mgonjwa amefika — ziara bado haijafungwa",
  refArrivedChpStatus: "Yuko kituoni.",
  refArrivedFacilityHeadline: "Mgonjwa yuko hapa — anza huduma",
  refArrivedFacilityStatus: "Mtu amefika.",
  refSeenHouseholdHeadline: "Anaonwa sasa",
  refSeenHouseholdStatus: "Kaa hadi ziara ikamilike.",
  refSeenChpHeadline: "Mgonjwa anaonwa — ziara bado haijafungwa",
  refSeenChpStatus: "Matokeo huja baada ya ziara kufungwa.",
  refSeenFacilityHeadline: "Anahudumiwa — funga ziara ukimaliza",
  refSeenFacilityStatus: "Rekodi kilichotokea huduma ikiisha.",
  refCompletedHouseholdHeadline: "Huduma imekamilika. Tunasubiri kusikia kilichotokea.",
  refCompletedHouseholdStatus: "Matokeo hayajarudi bado.",
  refCompletedChpHeadline: "Ziara imekamilika — inasubiri matokeo",
  refCompletedChpStatus: "Ufuatiliaji unategemea kile kituo kitakachorejesha.",
  refCompletedFacilityHeadline: "Ziara imekamilika — rejesha matokeo",
  refCompletedFacilityStatus: "Jamii inahitaji kujua kilichotokea.",
  refOutcomeHouseholdHeadline: "Hiki ndicho kilichotokea, na cha kufanya sasa",
  refOutcomeHouseholdStatus: "Kituo kimerejesha matokeo.",
  refOutcomeChpHeadline: "Matokeo yamerejeshwa — ufuatiliaji unaweza kuhitajika",
  refOutcomeChpStatus: "Kagua kama kaya hii inahitaji kutembelewa.",
  refOutcomeFacilityHeadline: "Matokeo yametumwa kwa jamii",
  refOutcomeFacilityStatus: "Yamerejeshwa.",
  refQueuedHouseholdHeadline: "Imehifadhiwa kwenye simu hii",
  refQueuedHouseholdStatus: "Huko mtandaoni. Rufaa itatumwa utakaporudi mtandaoni.",
  refQueuedChpHeadline: "Rufaa imepangwa — nje ya mtandao",
  refQueuedChpStatus: "Iko kwenye kifaa hiki. Tuma muunganisho ukirudi.",
  refNoResponseHeadline: "Kituo hakijajibu",
  refNoResponseHouseholdStatus: "Kaa mahali unapoweza kusafiri watakapojibu.",
  refNoResponseOtherStatus: "Rufaa imetumwa — kituo hakijajibu.",
  refNoResponseFacilityStatus: "{f} haijajibu bado.",

  actionSendNow: "Tuma sasa",
  actionSendFacility: "Tuma kwa kituo",
  actionSendReferral: "Tuma rufaa",
  actionAccept: "Kubali",
  actionWeveLeft: "Tumeondoka",
  actionTheyLeft: "Wameondoka",
  actionWeveArrived: "Tumefika",
  actionTheyreHere: "Wamefika",
  actionStartCare: "Anza huduma",
  actionCompleteVisit: "Kamilisha ziara",
  actionReturnOutcome: "Rejesha kilichotokea",

  expectedArrivalTpl: "anatarajiwa kufika baada ya dakika {m}",
  travelTpl: "Safari ya dakika {m}",

  failOfflineEyebrow: "Nje ya mtandao",
  failOfflineTitle: "Huko mtandaoni",
  failOfflineBody:
    "Tathmini bado inafanya kazi kwenye simu hii. Kutuma rufaa kutasubiri hadi urudi mtandaoni.",
  failNoResponseEyebrow: "Hakuna jibu",
  failNoResponseTitle: "Kituo hakijajibu",
  failNoResponseBody:
    "Rufaa imetoka kwenye simu hii. Kituo hakijajibu. Kaa mahali unapoweza kusafiri watakapojibu.",
  failRedirectedEyebrow: "Imeelekezwa kwingine",
  failRedirectedTitle: "Imeelekezwa kituo kingine",
  failRedirectedBody:
    "Kituo hiki hakiwezi kumpokea. Kituo kingine sasa kiko kwenye rufaa.",
  failStaleEyebrow: "Taarifa za zamani",
  failStaleTitle: "Taarifa hizi zinaweza kuwa za zamani",
  failStaleBody:
    "Kipimo kilichorekodiwa ni cha zamani mno kuongoza uamuzi wa leo kama kipimo kipya.",
  failIncompleteEyebrow: "Haijakamilika",
  failIncompleteTitle: "Tathmini hii haijakamilika",
  failIncompleteBody:
    "Hakuna taarifa za kutosha kufanya uamuzi huu kwa usalama. Jibu moja zaidi linahitajika.",
  failWeakEyebrow: "Muunganisho dhaifu",
  failWeakTitle: "Muunganisho ni dhaifu",
  failWeakBody:
    "Hii inaweza kuchukua muda zaidi. Njia ya huduma inabaki kwenye simu hii hadi utumaji uthibitishwe.",
  dangerEyebrow: "Dalili ya hatari",
  dangerTitle: "Usisubiri nyumbani na dalili hii.",
  dangerBody: "Nenda kupata huduma sasa.",
  watchEyebrow: "Angalia",
  watchTitle: "Nenda sasa dalili hizi zikianza",

  facilityEyebrow: "Kituo cha afya",
  facilityTravelTpl: "Dakika {m} kwa barabara ya kawaida",
  facilityCanTake: "Kituo hiki kinaweza kumpokea",
  facilityWeCanHandle: "Tunaweza kushughulikia rufaa hii",
  facilityMayNot: "Huenda kituo hiki kisiweze kumpokea",

  handoffEyebrow: "Makabidhiano",
  whyComingUrgent:
    "{who} anahitaji huduma ya dharura. Dalili za hatari zilibainika katika tathmini ya jamii.",
  whyComingToday: "{who} anapaswa kuonwa leo. Hii si hali ya kusubiri nyumbani.",
  whyComingDefault: "{who} yuko kwenye rufaa ya Tunza.",
  whoSubjectChild: "Mtoto kutoka kaya ya majaribio",
  whoSubjectSelf: "Mtu mzima (mwenyewe) kutoka kaya ya majaribio",
  whoSubjectOther: "Mtu kutoka kaya ya majaribio",
  handoffWho: "Nani",
  handoffDescribed: "Walichoeleza",
  handoffAwake: "Macho",
  handoffBreathing: "Kupumua",
  handoffDrinking: "Kunywa",
  handoffDuration: "Muda gani",
  handoffTemp: "Joto la mwili (jaribio)",
  handoffPhotoOnly: "Picha pekee (jaribio)",
  handoffNotDescribed: "Hakikuelezwa",
  handoffStillMissing: "Bado zinakosekana",
  whoValueSelf: "Mtu mzima (mwenyewe) · kaya ya majaribio",
  whoValueAdult: "Mtu mzima · kaya ya majaribio",
  whoValueChild: "Mtoto · kaya ya majaribio",
  whoValueUnknown: "Hajabainishwa · kaya ya majaribio",
  unknownValue: "Haijulikani",
  freshnessAssessedTpl: "ilitathminiwa dakika {m} zilizopita",
  freshnessOld: "ilirekodiwa miezi 8 iliyopita",

  outcomeQuestion: "Nini kilitokea?",
  outcomeTreated: "Alionwa na kutibiwa",
  outcomeHigher: "Alihitaji kituo cha ngazi ya juu",
  outcomeNoShow: "Hakufika",
  outcomeUnknown: "Matokeo hayajulikani",

  startEncounter: "Anza tathmini",
  noEncounter: "Hakuna tathmini inayoendelea",
  noEncounterDetail: "Anza moja kunasa kinachoendelea, kisha uamue.",
  noIncoming: "Hakuna rufaa inayokuja",
  noIncomingDetail: "Kaya au CHP akituma rufaa, itaonekana hapa.",
  otherActions: "Vitendo vingine",
  redirect: "Elekeza kwingine",
  askMore: "Uliza zaidi",
  needsAttention: "Inahitaji umakini",
  needsAction: "Inahitaji hatua",
  missingInformation: "Taarifa zinazokosekana",
  whoNeedsFollowUp: "Nani anahitaji ufuatiliaji",
  nothingWaiting: "Hakuna kinachosubiri",
  encounterTitle: "Tathmini",
  incomingTitle: "Zinazoingia",
  fuWatchHome: "Kaya ya majaribio — angalia dalili za hatari",
  fuWatchHomeDetail:
    "Walishauriwa kubaki nyumbani. Hakikisha bado anaweza kunywa na kuamka.",
  fuConfirmTravel: "Safari haijathibitishwa",
  fuConfirmTravelDetail: "Kituo kimekubali. Thibitisha kama kaya imeondoka.",
  fuPostOutcome: "Kaya ya majaribio — fuatilia baada ya huduma",
  fuPostOutcomeDetail: "Thibitisha wanapata nafuu nyumbani.",

  viewingAs: "Unaangalia kama",
  roleHousehold: "Kaya",
  roleChp: "CHP",
  roleFacility: "Kituo",
  demoLabel: "Demo",
  namedConditions: "Hali zilizotajwa",
  startOver: "Anza upya",
  languageButton: "English",
  languageAria: "Switch language to English",
  disclaimer: "Si mbadala wa huduma za dharura au matibabu ya kitaalamu.",

  contractObservedFacts: "Mambo yaliyotajwa",
  contractRetrievedEvidence: "Ushahidi ulioletwa",
  contractDerivedFeatures: "Vipengele vilivyokokotwa",
  contractHypotheses: "Mawazo",
  contractUncertainties: "Yasiyojulikana",
  contractContradictions: "Kinachokinzana",
  contractRequiredInformation: "Taarifa zinazohitajika",
  contractRedFlags: "Alama zilizorekodiwa",
  contractNextAction: "Hatua inayofuata",
  contractProvenance: "Chanzo",
};

const TABLES: Record<Locale, Record<CopyKey, string>> = { en, sw };

export function t(key: CopyKey, locale: Locale): string {
  return TABLES[locale][key];
}

/** Replace {name} placeholders in a copy template. */
export function fill(
  text: string,
  vars: Record<string, string | number>,
): string {
  return text.replace(/\{(\w+)\}/g, (match, name: string) =>
    name in vars ? String(vars[name]) : match,
  );
}

export const copyTables = TABLES;
